packages:
  - workflow
  - model
  - ui
  - test
  - .

catalog:
  '@platforma-sdk/workflow-tengo': ^1.7.0
  '@platforma-sdk/model': ^1.7.20
  '@platforma-sdk/ui-vue': ^1.7.27
  '@platforma-sdk/tengo-builder': ^1.16.0
  '@platforma-sdk/block-tools': ^2.3.19

  '@platforma-sdk/test': ^1.7.23
  '@milaboratories/helpers': ^1.6.6

  '@milaboratories/software-pframes-conv': ^1.6.4
  '@platforma-open/milaboratories.software-small-binaries': ^1.14.5
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-113-develop

  'vue': ^3.5.12
  'vue-tsc': 2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.2.3

  'vite': ^5.4.10
  'vitest': ^2.1.4
  '@vitejs/plugin-vue': ^5.1.4

  '@vueuse/core': ^11.1.0

  '@ag-grid-community/core': &ag-grid ^32.3.2
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid

  '@changesets/cli': ^2.27.9

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.5.2
  '@platforma-open/milaboratories.samples-and-data.model': ^1.4.2
