packages:
  - workflow
  - model
  - ui
  - test
  - .

catalog:
  '@platforma-sdk/workflow-tengo': ^1.6.1
  '@platforma-sdk/model': ^1.7.9
  '@platforma-sdk/ui-vue': ^1.7.9
  '@platforma-sdk/tengo-builder': ^1.14.13
  '@platforma-sdk/block-tools': ^2.3.17

  '@platforma-sdk/test': ^1.7.11
  '@milaboratories/helpers': ^1.6.5

  '@milaboratories/software-pframes-conv': ^1.6.1
  '@milaboratories/software-small-binaries': ^1.11.0
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-112-develop

  'vue': ^3.5.12
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.2.3

  'vite': ^5.4.9
  'vitest': ^2.1.3
  '@vitejs/plugin-vue': ^5.1.4

  '@vueuse/core': ^11.1.0

  '@ag-grid-community/core': ^32.2.2
  '@ag-grid-community/client-side-row-model': ^32.2.2
  '@ag-grid-community/vue3': ^32.2.2
  '@ag-grid-community/styles': ^32.2.2

  '@changesets/cli': ^2.27.9

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.5.2
  '@platforma-open/milaboratories.samples-and-data.model': ^1.4.2
