packages:
  - workflow
  - model
  - ui
  - test
  - .

catalog:
  '@platforma-sdk/workflow-tengo': ^2.1.0
  '@platforma-sdk/model': ^1.8.0
  '@platforma-sdk/ui-vue': ^1.8.18
  '@platforma-sdk/tengo-builder': ^1.16.1
  '@platforma-sdk/block-tools': ^2.3.24

  '@platforma-sdk/test': ^1.8.13
  '@milaboratories/helpers': ^1.6.6

  '@milaboratories/software-pframes-conv': 2.0.1
  '@platforma-open/milaboratories.software-small-binaries': ^1.14.6
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-133-develop

  'vue': ^3.5.12
  'vue-tsc': ^2.1.10

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.2.3

  'vite': ^5.4.11
  'vitest': ^2.1.5
  '@vitejs/plugin-vue': ^5.2.0

  '@vueuse/core': ^11.2.0

  '@ag-grid-community/core': &ag-grid ^32.3.3
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid

  '@changesets/cli': ^2.27.9

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.6.5
  '@platforma-open/milaboratories.samples-and-data.model': ^1.6.1
