packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^2.8.1
  '@platforma-sdk/model': ^1.20.6
  '@platforma-sdk/ui-vue': ^1.20.6
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/block-tools': ^2.4.12

  '@platforma-sdk/test': ^1.20.6
  '@milaboratories/helpers': ^1.6.10

  '@milaboratories/software-pframes-conv': 2.1.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.0
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-133-develop

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.3.3

  'vite': ^6.0.3
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@vueuse/core': ^12.0.0

  '@ag-grid-community/core': &ag-grid ^32.3.3
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid

  '@changesets/cli': ^2.27.10

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.8.8
  '@platforma-open/milaboratories.samples-and-data.model': ^1.8.2
