packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^3.0.1
  '@platforma-sdk/model': ^1.24.0
  '@platforma-sdk/ui-vue': ^1.27.2
  '@platforma-sdk/tengo-builder': ^2.0.0
  '@platforma-sdk/block-tools': ^2.5.23
  '@platforma-sdk/eslint-config': ^1.0.1

  '@platforma-sdk/test': ^1.24.1
  '@milaboratories/helpers': ^1.6.11

  '@platforma-open/milaboratories.software-mixcr': 4.7.0-139-develop

  'vue': ^3.5.13
  'vue-tsc': ^2.2.0

  'zod': ~3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.4.4

  'vite': ^6.2.0
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@vueuse/core': ^12.7.0

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.28.1

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.9.10
  '@platforma-open/milaboratories.samples-and-data.model': ^1.9.1
